/**
 * CyberCrowd-Core — Core NET Projection
 *
 * Purpose:
 * - Prepare a bounded operational projection for NET.
 * - Translate CORE-approved boundary decisions into immutable
 *   projection artifacts consumable by CyberCrowd-NET.
 *
 * Does NOT:
 * - create identity
 * - create ownership
 * - expose OSAR artifacts
 * - expose dissolved content
 * - expose behavioral history
 * - authorize actions
 * - mutate CORE state
 */

import {
  NetProjectionBoundaryResult,
} from "./net-projection-boundary";

export type CoreNetProjectionStatus =
  | "CORE_NET_PROJECTION_READY"
  | "CORE_NET_PROJECTION_BLOCKED"
  | "CORE_NET_PROJECTION_REVIEW";

export interface CoreNetProjection {
  /**
   * Artifact discriminator.
   */
  readonly status: CoreNetProjectionStatus;

  /**
   * Projection anchor generated by the boundary.
   */
  readonly projectionReference: string;

  /**
   * Whether this projection may continue into NET.
   */
  readonly readyForNet: boolean;

  /**
   * Creation timestamp.
   */
  readonly createdAt: string;
}

/**
 * Create a CORE projection from the NET boundary decision.
 *
 * Translation only.
 */
export const createCoreNetProjection = (
  boundary: NetProjectionBoundaryResult,
): CoreNetProjection => {

  let status: CoreNetProjectionStatus;
  let readyForNet = false;

  switch (boundary.status) {

    case "NET_PROJECTION_ALLOWED":
      status = "CORE_NET_PROJECTION_READY";
      readyForNet = true;
      break;

    case "NET_PROJECTION_BLOCKED":
      status = "CORE_NET_PROJECTION_BLOCKED";
      break;

    default:
      status = "CORE_NET_PROJECTION_REVIEW";
      break;
  }

  return Object.freeze({
    status,
    projectionReference: boundary.projectionReference,
    readyForNet,
    createdAt: new Date().toISOString(),
  });
};

/**
 * Structural validation only.
 */
export const validateCoreNetProjection = (
  projection: CoreNetProjection,
): boolean => {

  return (
    projection.projectionReference.length > 0 &&
    projection.createdAt.length > 0 &&
    (
      projection.status === "CORE_NET_PROJECTION_READY" ||
      projection.status === "CORE_NET_PROJECTION_BLOCKED" ||
      projection.status === "CORE_NET_PROJECTION_REVIEW"
    )
  );
};
